### ISSUE TITLE
workshop 6 - primer design module - Chris comments

### ISSUE THREAD

**Issue by cclarkson** [anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io#103]
Hi Sanjay, the primer design package is looking really nice, I love the plots. 
I have a few comments about the lecture:

* We think that your module probably best fits at the end of the workshop - module 4. The narrative of the workshop will then be - 
-1. Ooh haplotypes, they're cool 
-2. Selection scans, they're cool
-3. With our haplotypes and selection scans we could do beautiful science (find candidate resistance loci)
-4. With your primer design package we could validate those candidate resistance loci!
* As molecular biology experience was not a prerequisite for joining the course, it might be good to come in at a lower level, explain what PCR/qPCR is, how it works (diagram?) and what it is useful for in the context of vector control and particularly this workshop i.e. validate candidate loci (with examples).
* PRIMER RECAP - as above, some folk might not have met PCR/primers before.
* MOL BIO APPLICATION - Good place for some vector examples and some background.
* PRIMER DESIGN - this level of detail might be lost on some folk, terms will definitely need more explanation.
* SNPs/MUTATIONS - might need to explain figures and have introduced what qPCR is.
* ACE1 - nice example, more time explaining figure might help.
* ~16min - `sample_query = "taxon == 'coluzzii'"` would be in keeping with previous workshops.
* ~19min - maybe show some plots with "bad" primers as well.

**Comment by sanjaynagi** [comment]
Great feedback Chris, completely agree with it all. Had only put it as module 1 as Alistair mentioned previously but I agree this way is better. 

Are any of the other module drafts complete so that I may link it together even more?

**Comment by cclarkson** [comment]
Hi @sanjaynagi, unfortunately we are running a bit behind, so we won't get the other module drafts till early next week now, sorry. I'll give you a shout as soon as mine (module 3) is ready.
