### ISSUE TITLE
Workshop 6 - module 1 (designing primers) - feedback from Lee

### ISSUE THREAD

**Issue by leehart** [anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io#104]
Hi @sanjaynagi

Thanks for the great video! I learnt (or re-learnt) a lot. Nice clear sound quality. 

Sorry I don't have much feedback to offer. I’m probably not the target audience, so I definitely appreciated the primer on what a primer is!

A speaker video would probably add some character, if that’s an option.

Probably just me and my tired mind, but this module felt like it might have been a bit more technical or harder going than some of the previous modules. I had to look up a few of the terms and rewatch some parts, especially in the first 6 minutes, to be honest. So maybe the beginning could be made easier to follow, somehow.

Other than that, I thought it was a very interesting tutorial and no doubt it will be very useful. Thanks again!

**Comment by sanjaynagi** [comment]
Thanks Lee! 

I think if we incorporate Chris's comments, with some small intro to PCR and qPCR, and ill try and make sure everything else is relatively simple, itll be hopefully not too much more technical. Ill try and make sure I explain any terms. 

Definitely planning to add video of me, it was just for the draft. Which reminds me - how is everyone recording these videos? I just used kazam to screencast, I dont know if you guys have any recommendations @cclarkson @alimanfoo
