### ISSUE TITLE
Workshop 1 module 4 Analysing SNPs in the Vgsc - feedback from Kelly

### ISSUE THREAD

**Issue by KellyLBennett** [anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io#11]
Great job Chris. It was very clearly presented. I think you have a really difficult job here because there are a lot of concepts that have to be brought together and a lot of jargon that is necessary to the analysis. 

Here are my comments on the different sections. 

Although it makes sense to define the variables needed at the beginning, I feel this could be a point of confusion since the concepts haven't been introduced yet. Could this explanation be left until later or as something to come back to? (one idea is to leave it until after going through the different sections -snps, effects, cohorts, then summarise and explain that you need them for analysing the SNP frequencies). Or the explanation be simplified at the beginning i.e., by just saying that we need to input genomic data and populations (aka cohort and samples within that) and that variables can be defined and you'll show how to choose these. 

On first mentioning cohorts it would be good to mention this means population since it could be an unfamiliar term.

In the SNPs section, although you explain genotypes well, you do not explain the terminology SNP and how this relates. 
This may not really be needed but is there a way to show SNPs represented in a population? i.e. a diagram just showing that at the same site, different individuals have variants (like an alignment or similar) to help students think about this concept applied to their data. 

When explaining reference and alternate SNPs you talk about an allele being a variant. However, this could be slightly confusing in the context of the reference allele to those looking at the diagram since there is no variation between the reference and reference allele. You could think about using a different word here or avoiding its use.

I wondered if this was the point to bring up SNP frequencies rather than leaving it until after the cohorts. Perhaps the cohorts section could go at the beginning before SNPs to make it flow better?

When talking about non-syn and syn SNPs a diagram could reinforce the table.

I think the explanation of non-syn and syn SNPs is really nice. On the next step that follows when the SNP effects are show this is a potential point of confusion because the students may be wondering what the other types are. One idea is to say we are only really interested in non-syn SNPs and filter the table or maybe an explanation of SNP effects is not needed at all.

The description of cohorts is really nice. 

When talking about SNP frequencies could there be more emphasis on what this means for insecticide resistance, or examples in this context, to help drive home the message of why we are looking at SNP frequencies. I understand you may not want to give too much away since there will be a discussion on it.

**Comment by cclarkson** [comment]
discussion with Kelly
- Why are we doing this analysis, what can it for.
- SNP diagram - e.g. show individuals carry different SNPs (NS/S)
- be explicit - SNP is specific  type of allele (try not to say variant).
- Take a look at order  - Cohorts>SNPs>Freqs
- SNP effects - describe other effects or not?
