### ISSUE TITLE
Workshop 7 - module 2 (gene flow) - feedback from Lee

### ISSUE THREAD

**Issue by leehart** [anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io#110]
Thanks @alimanfoo

Another very interesting, informative, clear and well-presented video! Nice!

Sorry I've nothing substantial to feedback, only a collection of small incidental thoughts/comments:

- I suspect saying the "transfer" of genetic "material" from one population to another makes it sound like actual DNA (i.e. "material") is physically transferring (not like inheritance) between organisms (akin to viral horizontal gene transfer). Although I expect there is little risk of confusion. Perhaps genetic "information" or "code" would be more accurate? (Or maybe I've got the wrong idea.)

- Being another one for semantics, I really appreciated the clarification of the term "gene flow" at the beginning.

- I'm still trying to figure out if the adjectives "interspecific" and "interspecies" are interchangeable, and why the field seems to favour "interspecific". I suppose "interspecific" is useful when contrasting with "intraspecific". [which was soon confirmed, c. 6:26]

- 4:04 - I adore those cute little flies -- and their love stories! :-)

- 9:37 - It's probably too speculative, but I often wonder about the theoretical limits to (or expectations for) spatial gene flow, especially with disease vectors like gambiae. There seemed to be some conflicting ideas about what range was possible, when I last looked.

- 12:50 - I was expecting you to say something about how/why the two graphs of Population A and B might look the same or different, i.e. one might assume that the plot of allele frequency in Population B will eventually look identical to Population A (if all else was unnaturally equal) but simply shifted by 2 generations. I suppose they might have different curves depending on certain factors. (And now I suspect you might have purposely avoided a rabbit hole.)

- 15:34 - I reckon the point about gene flow's relevance to vector surveillance and control was very important and well made.

- 21:40 - It might be worth clarifying a little more why AIMs are not useful for detecting spatial gene flow. You're hinting at something about the sparsity or low resolution of AIMs, and I find myself trying to infer from the word "better" some sort of method with denser coverage. Although maybe this is just a brief introduction with more details to come. [which is soon confirmed]

- 24:01 - Sorry for interrupting us!

- 27:27 - The refresher on haplotype frequencies was very helpful

- 31:05 - At this point, I am still wondering how haplotypes are actually "extracted" from genomic windows. (Maybe you could touch on that somewhere between 28:48 and 29:17, unless I missed something.) 

- 40:20 - Intriguing.

- 41:21 - I imagine some trainees might ask why this isn't being determined algorithmically, rather than having to manually plot a chart and pick out a good window_size every time.

- Good important caveats at the end -- makes sense.

Great tutorial, thanks!

**Comment by alimanfoo** [comment]
Thanks so much Lee! I'll definitely keep the cute flies 😂
