### ISSUE TITLE
Workshop 7 - module 1, Sanjay feedback 

### ISSUE THREAD

**Issue by sanjaynagi** [anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io#111]
Hey Chris, (@cclarkson) 

No major comments from me, looks good. 

0.37 - strictly speaking only overexpression of Gste2 has been associated with OP resistance, not amplifications. Also, was just looking at the Adolfi ms, and its a little bit of a tentative association overall, as it only causes resistance to fenitrothion and not malathion. Might be worth stating it can confer resistance to **some** OPs? potentially important given we have no idea about effect on PM which is most important OP. 

Also, I was wondering if it might be useful to show a plot of copy number vs genotype, to show the relationship between the ACE1 CNV and G280S, such as in this notebook https://colab.research.google.com/drive/1m5nOqPH_73Kn6AD4cUQr3b1N7z3o-QDu#scrollTo=7RxQ08KKDMZ1

**Comment by sanjaynagi** [comment]
example G280S v ACE1 Copy number

![cnv_genotype](https://user-images.githubusercontent.com/34922269/198281068-ac2be696-06c0-4c80-92e2-ca2c3e316be5.png)

**Comment by sanjaynagi** [comment]
example, G280S v ACE1 Copy number:
![cnv_genotype](https://user-images.githubusercontent.com/34922269/198281303-c4e81a2f-2fab-4ccb-8029-64a0777399b8.png)

**Comment by cclarkson** [comment]
Hi @sanjaynagi, many thanks for the comments. The CNV vs. genotype plot is a great idea.
