### ISSUE TITLE
Workshop 7 - module 1 (SNP & CNV frequencies) - feedback from Lee

### ISSUE THREAD

**Issue by leehart** [anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io#112]
Thanks @cclarkson

Another fascinating and informative video, very well presented. Merci beaucoup !

I didn't spot any problems. Here are my notes:

- Nice clear audio. Maybe a tad bassy, but nothing to worry about.

- 3:23 - I had to rewatch the section on organophosphates a few times, but I reckon that's just because it's relatively unfamiliar to me, and I'm a bit daft! It seemed there was a fair bit for me to unpack there before I felt I understood it.

- 5:25 - I suspect that "West" and "Central" should only be capitalised when referring to a people or an actual proper place name or organisation, e.g. the Central African Republic, and lowercase when indicating a general geographical region, but that convention does not seem universally adhered to, so I doubt myself. The UN defines "Western Africa" and "Middle Africa" (in UN M49), while others define "Central Africa", so I suppose strongly/officially defined sets make sense as proper names.

- 22:45 - Heatmaps are so cool, they should be named coolmaps ;-)

Cheers!

**Comment by cclarkson** [comment]
Hi @leehart, thanks for the comments. OP function/resistance is a bit complicated, I'll try to maker it clearer in the next cut.

Coolmaps :)
