### ISSUE TITLE
Workshop 7 - module 3 (haplotype clustering) - feedback from Lee

### ISSUE THREAD

**Issue by leehart** [anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io#113]
Thanks @sanjaynagi

Another very interesting and informative video, well presented!

Sorry I can't advise wrt window sizes.

Not much to feed back, just a few minor observations:

- The sound volume seems very low, for some reason, although the general sound quality is otherwise crisp. (I had to turn my volume to maximum, and it was still hard for me to hear, unlike other videos.) I suspect it might be solved by simply having the mic closer, because it was louder when you accidentally hit the mic, circa 0:22, and when you leaned in closer, circa 0:58. Or maybe  there is a sensitivity setting that could be adjusted?

- 10:30 - I noticed that although the numbers for the distance change between different linkage methods, in this case, the general shape of the two dendrograms still look similar (only stretched/compressed). I'm left wondering: can we expect to see markedly different structures of dendrogram between different linkage methods?

- 12:18 - I reckon "Its" should be "It's" there. See, I'm useful! ;-)

- 25:13 - I started to feel that there had been many examples of similar things, and worried that I was missing some subtle points.

- Good exercises at the end, and an important follow-up question about what is driving sweeps, imo.

Evidently a very intriguing topic, with some powerful tools for insight.

Great stuff, cheers!

**Comment by sanjaynagi** [comment]
Thank you Lee! that's great. 

I also noticed the quiet mic, I had meant to mention it. I was using a proper microphone but it wasn't immediately in front of me so I think you are right, ill make sure that's corrected when I do the video! :)

**Comment by leehart** [comment]
With regards to your recent redraft, thanks again @sanjaynagi

Well presented with great explanations. Only a couple of very minor things that I noted:

- 2:57 - The animation and talk-through of successive clustering was very helpful and clear.
- 21:45 - It's a little difficult to discern the different plot symbol shapes, from my view, although I appreciate you probably can't do much about that. [You pick up on a similar issue around 25:00, but I suspect it is even less clear in the video, maybe because of lower resolution, etc. -- Again, probably something for API dev, maybe we can use different shapes that are more visually distinct, or I suspect it's not such a problem outside of video.]

Very interesting caveats and exercises at the end.

Cheers!

**Comment by sanjaynagi** [comment]
Thanks Lee. good point about the video resolution for the shapes... didn't think of that at all :( 

unfortunately I didn't have time to re-do this/ i think however much I zoom in it will always be difficult to see as the points rescale. Hopefully the trainees trust what i say!
