### ISSUE TITLE
W7M4 feedback from Alistair

### ISSUE THREAD

**Issue by alimanfoo** [anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io#119]
Hi @cclarkson, draft looks great, sorry about the bug with colouring networks by country and the grey pie wedges - I fixed that now so malariagen_data v7.0.3 should work fine.

Some comments below but I know time is short so feel free to ignore :)

Suggest module title "Investigating gene flow at a locus of interest - haplotype networks".

s/movement of insecticide resistance loci/gene flow at insecticide resistance loci/

s/analyse the spread of insecticide resistance associated loci/analyse gene flow at loci associated with insecticide resistance/

s/discern movement of resistance loci/find evidence for gene flow events between countries or species/

I.e., it's not loci that move or spread.

Don't think we need to mention the "server port" parameter here.

Restart browser needed? Or refresh page works?

Adding server_mode="inline" shouldn't be required, it's the default parameter value.

Emphasise "gamb_colu" is the haplotype phasing analysis.

Choose the first example to be network a little simpler. E.g., slightly smaller genome region so network is less tangled. Could try e.g., 40kb around kdr.

Of course you will want to move the nodes to make the figure look pretty for your nature paper! Btw you can shift click to select multiple nodes and then drag to move them all at the same time - so much fun to be had!!

Using simpler example would also be better when you increase the max_dist parameter, as easier to see what's changed from max_dist 2.

Not sure about the explanation for the max_dist parameter. It's not really about increasing or decreasing the amount of evidence for something. Increasing max_dist just allows finding connections between more distantly related groups of haplotypes. But we choose max_dist 2 mainly because we're interested here only in groups of very closely related haplotypes, which are therefore very likely to share a recent common origin. (And increasing max_dist also increases the time taken to build the networks, which is pointless if we're not interested in those more distant connections.)

When explaining how to interpret networks, any chance to make it a bit gentler, and connect with idea of selective sweeps. Some points here to get across:

* When mutation occurs, haplotype comes under selection and goes to high frequency. So we're interested here especially in the large nodes because these are high frequency haplotypes experiencing positive selection.

* During a selective sweep, some additional mutations will occur on the original haplotype. These could be neutral, could be secondary functional, but key point is that these additional mutations occur, and give us a network of closely related haplotypes. We can infer that each network of connected haplotypes have a recent common origin.

* If a network of connected haplotypes contains haplotypes from two or more countries, this is evidence for adaptive gene flow. Particularly if you have a large node containing haplotypes from multiple countries, this is very strong evidence for adaptive gene flow because exactly the same haplotype is found in both.

Explaining why Ace1 don't see all the haplotypes, we're only interested in high frequency haplotypes and networks of closely related haplotypes because these are likely to be haplotypes under recent positive selection.

Shame we can't get same colours for countries in networks and dendrograms, would be cool if they matched. I might look at that.

**Comment by cclarkson** [comment]
@alimanfoo  - thanks super useful comments, I will get a final version to @jonbrenas today.
