### ISSUE TITLE
Workshop 1 - Module 1 : Interactive cloud computing with Google Colab (feedback from Kathryn)

### ISSUE THREAD

**Issue by kathryn1995** [anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io#14]
1. I like the start where you lay out the learning objectives. I would maybe hold off on explaining what Colab is until you have finished that part, then scroll down to the section on 'what is Colab' and do the little explanation there. It's nice to have some words on the screen relating to what you're saying. The same for explaining what a notebook is. 
2. When you're going through the learning objectives I would hold off on trying to explain them as you go. For example, saying they should be able to explain what a notebook is and then trying to explain it here. Hold off on the explanation until you get to that section, otherwise, the learning objectives can get a bit overwhelming. 
3. Might be worth mentioning that there are course notes and where to find them
4. A cheat sheet of some of the keywords might be nice (e.g. input/ output, variable, library/package, function, using shift+ENTER)
5. Might be worth mentioning that you have to be careful about running things in sequence. When you are moving cells about it can trip people up
6. For markdown is there a reason you don't use the toolbar for formatting? 
7. Might be worth stating at the beginning what level of python you expect and the depth of understanding you want people to take away so they're aware before they start seeing functions etc. and get overwhelmed if they don't understand it. 
8. Quickly explain what an operating system is when you mention it, give example e.g. Windows, mac, linux
9. API might be too complicated of a term to use without explaining it  
10. You say add an exclamation mark, but type a question mark to get documentation. It might be nice to move this section to just after you explain how to install something, before the plots 
11. Couldn't see the share button because of the video, could maybe just drag the browser so people can see 
12. It would be nice to summarise the key points you expect people to take away at the end and link it back to the learning objectives

**Comment by alimanfoo** [comment]
Hopefully mostly resolved via [new recording and lecture notes](https://anopheles-genomic-surveillance.github.io/workshop-1/module-1-colab.html), thanks again @kathryn1995 :pray:
