### ISSUE TITLE
W* - error message installing malariagen_data regarding dependency conflicts

### ISSUE THREAD

**Issue by KellyLBennett** [anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io#142]
Workshop 1 module 3. Although this does not impact the running of the notebook on Colab, I encounter an Error message on !pip install -q malariagen_data about bokeh installation.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
panel 0.14.4 requires bokeh<2.5.0,>=2.4.0, but you have bokeh 3.1.1 which is incompatible.

**Comment by ahernank** [comment]
Will keep this one open but we won't address it as part of the maintenance for the 2nd iteration.

**Comment by alimanfoo** [comment]
Thanks @ahernank. 

For the record, this error message can be safely ignored. It is telling us that the panel package requires an earlier version of bokeh, but we are not using panel at all, so everything should run fine.

I know this error message is a bit ugly but there's not much we can do about it for the time being, as malariagen_data requires bokeh 3.1 or greater. Hopefully colab will upgrade their environment soon.

**Comment by alimanfoo** [comment]
If we don't want users to see the error message, this looks like it would be an option:

```
!pip install -q --no-warn-conflicts malariagen_data
```

**Comment by ahernank** [comment]
If we want to suppress the error outputs more generally, we can could use: 

```
!pip install -qq malariagen_data
```

**Comment by alimanfoo** [comment]
> If we want to suppress the error outputs more generally, we can could use:
> 
> ```
> !pip install -qq malariagen_data
> ```

That looks better, let's do that.

**Comment by ahernank** [comment]
Suggest changing the title on this issue to: `W* - error message installing malariagen_data regarding dependency conflicts`; as a reminder to update this for all workshops.

**Comment by ahernank** [comment]
Actually, will have to use (as this is an error rather than a warning, my bad): 

```
!pip install -qqq malariagen_data
```

**Comment by jonbrenas** [comment]
It still shows an error, though:
<img width="1301" alt="Screenshot 2023-06-06 at 11 36 27" src="https://github.com/anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io/assets/51911846/782558bb-5ab3-4cfd-8d0f-b6b122dfe8af">

**Comment by ahernank** [comment]
Ack, thanks Jon. Will update to use Alistair's solution above.
