### ISSUE TITLE
W1M1-M4 - Sharing notebooks

### ISSUE THREAD

**Issue by jonbrenas** [anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io#146]
![Screenshot 2023-05-25 at 15 49 55](https://github.com/anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io/assets/51911846/1bb1095a-ec53-498b-855a-d38d4c25840c)

I was wondering if that instruction a the end of the notebook for all modules of the first workshop needed to be removed given that we stopped asking for notebooks afterwards (and I am not sure we are going to check them this time). Or is it just for them to check that they know how to share a notebook?

**Comment by ahernank** [comment]
Agree (I think even if we ask for them, this wouldn't be on Slack), maybe we could generalise it to something like:

> After you have finished running the code, working through the exercises and exploring the outputs; you can share your notebook using the `Share` function. This will allow you to create a direct link which can be shared with your peers.

**Comment by ahernank** [comment]
I realised that we already have a section in W1M1 on `Sharing notebooks via Google Drive`, so will update the text in there from `An easy way to share is to create a link, which you can then copy and paste into an email or slack channel to share with colleagues.` to `An easy way to share is to create a link, which you can then copy and paste to share with colleagues.`

Will also delete the EN/FR versions of:

```
When you've had enough, create a link to your notebook,
and share it with someone. If you're attending a training 
workshop, paste the link into the workshop slack channel.

```
, per Jon' suggestion above. These instructions are only present on W1 modules.
