### ISSUE TITLE
W1M2 - broken link to ipyleaflet document and Map function

### ISSUE THREAD

**Issue by harbi811** [anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io#149]
The link to ipyleaflet basemaps documentation in the exercise (Question 5) does not work anymore

The link in the notebook is https://ipyleaflet.readthedocs.io/en/latest/api_reference/basemaps.html
The current link is: https://ipyleaflet.readthedocs.io/en/latest/map_and_basemaps/basemaps.html

Link to `Map()` does not work
![image](https://github.com/anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io/assets/47387425/53b1727f-9443-4e10-a1ca-cdba45944444)

Link in notebook: https://ipyleaflet.readthedocs.io/en/latest/api_reference/map.html
Current link: https://ipyleaflet.readthedocs.io/en/latest/map_and_basemaps/map.html

**Comment by ahernank** [comment]
Having an issue updating this NB as ipyleaflet doesn't seem to be properly rendering the maps background on the HTML when using the HTTP server in datalab (although it is showing just fine on the notebooks when running them).., will keep trying with this one.

**Comment by ahernank** [comment]
>  ipyleaflet doesn't seem to be properly rendering the maps background on the HTML when using the HTTP server in datalab

Solved by using ipyleaflet==0.17.0.
