### ISSUE TITLE
W2M2 - Incorrect links in notebook and inconsistent naming of notebook

### ISSUE THREAD

**Issue by harbi811** [anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io#155]
There are broken links in the W2M2 notebook

1. The link to Lucas et al, 2019 paper is **https://https//pubmed.ncbi.nlm.nih.gov/31345938/** but it should be https://pubmed.ncbi.nlm.nih.gov/31345938/
2. The link to Simma et al, 2018 is **https://https//onlinelibrary.wiley.com/doi/10.1002/ps.5374** but it should be https://onlinelibrary.wiley.com/doi/10.1002/ps.5374
3. The link to David et al, 2005 is https://https//www.pnas.org/doi/abs/10.1073/pnas.0409348102 but it should be https://www.pnas.org/doi/abs/10.1073/pnas.0409348102

When the notebook is launched from the website, it is named as below, the first words up to "The genetic basis ..." could be removed
<img width="661" alt="image" src="https://github.com/anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io/assets/47387425/8e450785-b57d-4265-925b-27eded0b14a5">

**Comment by ahernank** [comment]
On the NB name when launched in colab, I haven't been able to update it to the full title as in the other notebooks but only to use the name of the original ipynb; so this is `module-2-metabolic-ir.ipynb` for now.

**Comment by ahernank** [comment]
I will close this one for now but if we are planning on making all titles consistent (rather than just correct), we should open a specific issue to track this.
