### ISSUE TITLE
W3M1 - Image not sourced from gcs

### ISSUE THREAD

**Issue by jonbrenas** [anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io#168]
The image is not currently hosted on gcs. It is also not scaled.

<img width="1157" alt="Screenshot 2023-06-15 at 12 38 56" src="https://github.com/anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io/assets/51911846/8b930064-d49f-40ea-8f85-3546d5894479">

**Comment by ahernank** [comment]
For this round of checks we are only updating the images/diagrams that come from viewer.diagrams, as these ones seem to cause the google permissions pop-up. If we want to make sure we source all images from GCS (probably the right thing to do!), we will need a new issue covering all workshops.
