### ISSUE TITLE
W6M3 - minor modifications

### ISSUE THREAD

**Issue by harbi811** [anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io#178]
1. Denote `results_cache`  as code in the notebook
<img width="594" alt="image" src="https://github.com/anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io/assets/47387425/e79e8b3b-88c7-44c3-816c-4df2ac7ffd80">

2. The link to Garud's 2015 paper on H12 is incorrect. The correct link is https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1005004. The link is used twice in this section
<img width="591" alt="image" src="https://github.com/anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io/assets/47387425/efe71d2f-5beb-43bd-a0d2-10105c6225f6">

**Comment by cclarkson** [comment]
resolved by #184
