### ISSUE TITLE
W7M1 - Minor corrections

### ISSUE THREAD

**Issue by jonbrenas** [anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io#179]
The link to Workshop 2 Module 4 in this paragraph is obviously broken when used from Colab:

![Screenshot 2023-06-26 at 15 28 53](https://github.com/anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io/assets/51911846/fc82dcab-800a-4508-b7bf-2c5eecece6a0)

The French paragraph at the end is missing some text:
![Screenshot 2023-06-26 at 15 31 47](https://github.com/anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io/assets/51911846/10720bd5-a4be-4c1e-912d-cc63d897f00b)

It should be something like:
`## Practical exercise - _Gste2_

### English 

The _Gste2_ gene encodes an epsilon-class glutathione-S-transferase. It was initially studied in _An. gambiae_ because its ortholog in the dengue and yellow fever vector _Aedes aegypti_ has been linked to DDT resistance through increased gene expression.

One study looking at amino acid substitions in _An. gambiae_ _Gste2_ found two mutations that in some cohorts were associated with insecticide resistance ([Lucas et al. 2019](https://www.nature.com/articles/s41598-019-49892-6)). L119V was associated with permethrin (a type of pyrethroid) resistance and I114T was associated with both permethrin and DDT. Previously, [Mitchell et al. 2014](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3968025/) found that _Gste2_ I114T conferred DDT resistance in _An. gambiae_ and _An. coluzzii_. 

The I114T mutation was also found to be associated with a CNV amplification that appeared to have fixed heterozygosity, much like with _Ace1_. The gene had duplicated, so that a wild-type gene and a I114T resistance mutation carrying gene were found on the same haplotype.

To further complicate the insecticide resistance story of _Gste2_ (and bring it into the scope of this module!) it has also been shown that overexpression of _Gste2_ is associated with OP resistance ([Adolfi et al. 2019](https://www.pnas.org/doi/10.1073/pnas.1914633116)). 
   
So, for this module's practical excercise, I would like you run a case study on amino acid and CNV frequencies in _Gste2_, using the same analytical approach as we used for _Ace1_ and the _An. coluzzii_ samples from Ag3.0.

### Français

_Gste2_ code pour une glutathion-S-transférase de classe epsilon. Il a été initialement étudié chez _An. gambiae_ car son orthologue chez le vecteur de la dengue et de la fièvre jaune _Aedes aegypti_, a été connecté à une résistance au DDT par augmentation de l'expression génique.

Une étude observant les substitutions d'acides aminés chez _An. gambiae_ pour _Gste2_ a trouvé deux mutations qui pour certaines cohortes étaient associées à une résistance aux insecticide ([Lucas et al. 2019](https://www.nature.com/articles/s41598-019-49892-6)). L119V était associée à une résistance à la perméthrine (un type de pyrethrinoïde) et I114T était associée à une résistance à la fois à la perméthrine et au DDT. Précédemment, [Mitchell et al. 2014](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3968025/) a montré que _Gste2_ I114T confère une résistance au DDT chez les _An. gambiae_ et les _An. coluzzii_.

La mutation I114T était aussi associée à une amplification des CNVs, qui semble avoir une hétérozygotie fixée, de manière très similaire à _Ace1_. Ce gène était dupliquée, de telle sorte qu'un gène contenant l'allèle sauvage et un gène contenant I114T, l'allèle de résistance se trouvaient dans le même haplotype.

Pour compliquer encore l'histoire de la résistance aux insecticides liée à _Gste2_ (et la rapprocher du sujet de ce module!), il a aussi été montré que la surexpression de _Gste2_ est associée à une résistance aux OPs. ([Adolfi et al. 2019](https://www.pnas.org/doi/10.1073/pnas.1914633116)). 

Donc, pour l'exercice pratique de ce module, je voudrais que vous étudiez les fréquences des substitutions d'acides aminés et ses CNVs pour _Gste2_ en utilisant la même approche analytique que nous avons utilisée pour _Ace1_ et les échantillons de _coluzzii_ d'Ag3.0.`

The exercises immediately afterwards have not been translated. The translation is:

`**1. Etudier les fréquences des acides aminés pour _Gste2_.**  _Indice: transcript="AGAP009194-RA"_.
 - Pourquoi est-ce que la numérotation des positions des acides aminés set décroissante (contrairement au cas d'_Ace1_)?
  

**2. Examiner les CNVs dans cette région.** _Indice: region="3R:28,597,652-28,598,640"_
 - Afficher le diagramme `cnv_hmm_heatmap` pour cette région - quels CNVs sont présents?
 - Etudier les fréquences des CNVs pour  _Gste2_.
  

**3. Concaténer les DataFrames des fréquences des acides aminés et des fréquences des CNVs.**
  

**4. Visualiser le DataFrame obtenu par concaténation sous forme de heatmap.** _Indice: ne pas oublier de sélectionner les colonnes avant._
 - Y a-t-il des motifs clairs d'association enter les SNPs et les CNVs associés à la résistance aux insecticides, comme observé pour _Ace1_? Pourquoi cela?
  

**5. Si sous souhaitez explorer ces analyses et leurs interprétations plus en profondeur...**
 - En tant qu'exercice optionel, les études de cas pour _Ace1_ et _Gste2_ peuvent être répétées pour  _An. gambiae_ au lieu d' _An. coluzzii_. _Indice: se souvenir que la distribution des _An. gambiae_ couvre une région plus vaste que celle des _coluzzii_.`

**Comment by ahernank** [comment]
@jonbrenas I will re-name this one to W7M1.
