### ISSUE TITLE
W6M4 - KeyError in notebook  and minor corrections

### ISSUE THREAD

**Issue by harbi811** [anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io#182]
1. The example in the notebook on designing primers for ACE1 region returns a KeyError while converting primer3 results to a pandas df
<img width="923" alt="image" src="https://github.com/anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io/assets/47387425/1fba1279-e364-4d1f-96f7-ca4205c63e50">

3. The link to the primer3 2.3.7 manual needs to be updated. 
<img width="514" alt="image" src="https://github.com/anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io/assets/47387425/7489f7c6-3ec8-461c-8afc-c6a8d3796401">

**Comment by cclarkson** [comment]
I have reached out to Sanjay.

**Comment by cclarkson** [comment]
resolved by #184
