### ISSUE TITLE
Use %pip instead of !pip

### ISSUE THREAD

**Issue by alimanfoo** [anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io#193]
Jupyter notebooks generally support a `%pip` line magic command, which runs pip and is guaranteed to install packages into whatever environment is being used to run the current kernel.

The more general `!pip` can be used to run pip as a system command, which will install packages into the base environment.

On colab, either works the same. However, on Amazon Sagemaker Studio Lab, `%pip` is required to ensure packages are installed in the current environment. This is probably a generally safer option.

For future compatibility with sagemaker lab, suggest we switch over notebooks here to using `%pip`.

**Comment by jonbrenas** [comment]
It is possible to figure it out from the references but I think it might help to have a list of PRs addressing this in order:

<s>W1M1: probably #195 (merged) </s>
<s>W1M2: probably #195 (merged) </s>
<s>W1M3: probably #195 (merged) </s>
<s>W1M4: probably #195 (merged) </s>

<s>W2M1: probably #201 (merged) </s>
<s>W2M2: No package is installed</s>
<s>W2M3: probably #201 (merged) </s>
<s>W2M4: probably #201 (merged) </s>

<s>W3M1: No package is installed</s>
<s>W3M2: No package is installed</s>
<s>W3M3: probably #210 (merged) </s>
<s>W3M4: probably #210 (merged) </s>

<s>W4M1: No package is installed</s>
<s>W4M2: No package is installed</s>
<s>W4M3: probably #218 (merged) </s>
<s>W4M4: probably #218 (merged) </s>

<s>W5M1: #239 (merged) </s>
<s>W5M2: No package is installed</s>
<s>W5M3: probably #228 (merged)</s>
<s>W5M4: #244 (merged)</s>

W6M1: #229
<s>W6M2: No package is installed</s>
W6M3: #231
W6M4: #230

W7M1: #232
W7M2: #240
W7M3: #243
W7M4: None yet

<s>W8M1: No package is installed</s>
<s>W8M2: No package is installed</s>
<s>W8M3: No package is installed</s>
<s>W8M4: No package is installed</s>

**Comment by jonbrenas** [comment]
All branches have been merged.
