### ISSUE TITLE
Workshop 1 (third iteration) - Update links

### ISSUE THREAD

**Issue by harbi811** [anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io#196]
**Introductory page**
1. update link to list of Python tutorials under *many excellent tutorials* text

![image](https://github.com/anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io/assets/47387425/d8ef53d3-407c-46a7-b7ce-7e3563853124)

**In W1M2,** 

1. the link to the Ag1000 phase 3 data resource does not work. This is the link in the notebook (https://malariagen.github.io/vector-data/ag3/intro.html)
Please see attached screenshot to find the section in the notebook

![image](https://github.com/anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io/assets/47387425/75a8bfe5-ebf0-47df-993d-b8f261e6dd74)

3. The link to the `sample_metadata()` function also needs to be updated. This is thelink in the notebook (https://malariagen.github.io/vector-data/ag3/api.html#sample-metadata). The documentation for this function can be found here https://malariagen.github.io/malariagen-data-python/latest/Ag3.html#sample-metadata-access

**In W1M4,**

1. the link to `snp_allele_frequencies()` function should be updated to 
(https://malariagen.github.io/malariagen-data-python/latest/generated/malariagen_data.ag3.Ag3.snp_allele_frequencies.html#malariagen_data.ag3.Ag3.snp_allele_frequencies)

![image](https://github.com/anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io/assets/47387425/4ef245a9-64fc-404b-93b9-f81c57610322)

2. Update link to `plot_frequencies_heatmap()` to https://malariagen.github.io/malariagen-data-python/latest/generated/malariagen_data.ag3.Ag3.plot_frequencies_heatmap.html#malariagen_data.ag3.Ag3.plot_frequencies_heatmap

4. Update link to `plot_frequencies_time_series()` to https://malariagen.github.io/malariagen-data-python/latest/generated/malariagen_data.ag3.Ag3.plot_frequencies_time_series.html#malariagen_data.ag3.Ag3.plot_frequencies_time_series

5. Update link to `plot_frequencies_interactive_map()` to https://malariagen.github.io/malariagen-data-python/latest/generated/malariagen_data.ag3.Ag3.plot_frequencies_interactive_map.html#malariagen_data.ag3.Ag3.plot_frequencies_interactive_map

**Comment by ahernank** [comment]
Thanks @harbi811! Apologies, would you mind expanding on what needs changing on the intro page here? I feel like I might be missing something here.
