### ISSUE TITLE
Workshop 2 (third iteration) - Update links

### ISSUE THREAD

**Issue by harbi811** [anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io#197]
**In W1M1**

1. Update link to `sample_metadata()` function with https://malariagen.github.io/malariagen-data-python/latest/generated/malariagen_data.ag3.Ag3.sample_metadata.html#malariagen_data.ag3.Ag3.sample_metadata

2. Replace `geneset()` function with `genome_features()` function found here https://malariagen.github.io/malariagen-data-python/latest/generated/malariagen_data.ag3.Ag3.genome_features.html#malariagen_data.ag3.Ag3.genome_features

3. Update link to `snp_allele_frequencies()` with https://malariagen.github.io/malariagen-data-python/latest/generated/malariagen_data.ag3.Ag3.snp_allele_frequencies.html#malariagen_data.ag3.Ag3.snp_allele_frequencies

**In W2M4**

1. update link to `gene_cnv_frequencies()` with https://malariagen.github.io/malariagen-data-python/latest/generated/malariagen_data.ag3.Ag3.gene_cnv_frequencies.html#malariagen_data.ag3.Ag3.gene_cnv_frequencies

2. update link to `plot_frequencies_time_series()` to https://malariagen.github.io/malariagen-data-python/latest/generated/malariagen_data.ag3.Ag3.plot_frequencies_time_series.html#malariagen_data.ag3.Ag3.plot_frequencies_time_series

3. update link to `gene_cnv_frequencies_advanced()` with https://malariagen.github.io/malariagen-data-python/latest/generated/malariagen_data.ag3.Ag3.gene_cnv_frequencies_advanced.html#malariagen_data.ag3.Ag3.gene_cnv_frequencies_advanced
This function appears twice in the notebook

5. update link to `plot_frequencies_interactive_map()` with https://malariagen.github.io/malariagen-data-python/latest/generated/malariagen_data.ag3.Ag3.plot_frequencies_interactive_map.html#malariagen_data.ag3.Ag3.plot_frequencies_interactive_map

**Comment by ahernank** [comment]
Thanks @harbi811! Am I right to assume both of these issues are in W2 (rather than W1 on the first module)?

**Comment by harbi811** [comment]
Oh yes. My apologies for the error.
