### ISSUE TITLE
W3M3 - Update map of GC locations and link to IGV docs

### ISSUE THREAD

**Issue by harbi811** [anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io#207]
I found two minor issues listed below

1. update map of Google Cloud locations
2.  Update link to IGV alignment track docs to https://igv.org/doc/desktop/#UserGuide/tracks/alignments/viewing_alignments_basics/#alignment-track

**Comment by ahernank** [comment]
Thanks @harbi811. I'll leave the current image of GC locations for simplicity as the new one seems to add proposed ones only, and the region labelling might raise some questions.
