### ISSUE TITLE
Workshop 2 - module 1 (Pandas DataFrames) - feedback from Lee

### ISSUE THREAD

**Issue by leehart** [anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io#36]
@alimanfoo 
Very clear, friendly, informative and easy to follow. Lots of essential info. This should polish up very nicely indeed!

Again, only very minor thoughts to share on the first draft:

- No concerns about the sound quality in general — very clear. Except there was one severe distortion around the 11:57 to 12:04 time, and the occasional distraction/interruption of notification sounds (e.g. 16:09, 21:41, 36:39)
- The position of the presenter video on the screen seems to work well — ideal.
- To my eye, the framing of your head sometimes looks a little low, i.e. you might want slightly less space above your head and more shoulder/torso, although this was intermittently improved whenever you sat/leaned forward. (Not very important, obviously.) 
- 1:43 - Has Markdown (or general text formatting) been introduced yet? Vague memory that it has, but it might be worth briefly mentioning it when first using it here again.
- 2:22 - Slight inconsistency in your pronunciation of “often”. Fwiw, I reckon either way is fine. Some regard the hard “t” as a hypercorrection, but I suspect it’s still debated and in flux. (My own pronunciation also varies, either due to or despite some amateur orthoepy.)
- 3:20 - Sounds a bit defensive wrt rationale for the tutorial. Maybe if the explanation was delivered a little more softly, that might be more consistent with the helpful stance.
- 5:06 - Although it’s mentioned later (circa 9:35) maybe mention that `df` is short for DataFrame on the first use, just to nip that curiosity in the bud.
- 5:30 - Does each row of the `df_samples` DataFrame really/technically represent a mosquito? Or would it be more accurate to say that it represents one “sample” of a mosquito, as there might be many samples from the same mosquito, in principle? That would seem to be consistent with the term “sample”, which is also used in the variable and function names. Maybe “mosquito” is technically accurate or an unnecessary distinction to make here, I’m not sure. I see it helps relate data to the natural world.
- 6:33 - I’d be tempted to mention that the “dot dot dot” is also (more formally) called an “ellipsis”, but that might just sound pretentious rather than actually being helpful!
- 7:30 - I sometimes wonder if the `start` and `end` positions are inclusive. I assume that “end” 48111 includes the position 48111, rather than meaning “up to position 48110 and no further”. Considering that the pandas slicing uses an exclusive `end` position, I imagine this ambiguity might cause confusion.
- 9:15 - When mentioning the cohort label, it might also be worth explaining, briefly, the number after country code, e.g. BF-07. (Asking for a friend.)
- 9:35 - Maybe mention the `df` variable name choice/freedom earlier, when first used, c. 5:30. Btw, one benefit of the `_df` suffix style is the visual semantic grouping, e.g. `foo_df`, `foo_int`, `bar_df`, `bar_int`, which I suppose is similar to file name extensions (`foo.png`, `bar.ipynb`) where the identifier part of the name is deemed more semantically important (or more desirable to notice or sort, etc.) than the type, i.e. (`foo` and `bar`) versus (`df` and `int`). This particular “style war” reminds me of something TBL supposedly said: “I would have skipped on the double slash - there’s no need for it. Also I would have put the domain name in the reverse order - in order of size” … Sounds like we were just one iced tea away from http:/[com.google](http://com.google/)
- 13:54 - Is HG2G really your favourite book?! (I would have guessed LOTR.) I must admit, I went down a rabbit-hole trying to figure out whether the 5M figure for Marvin’s “intelligence” was actually justifiable! Presumably the 5M figure comes from 50K multiplied by 100 IQ, but… :-) Fun!
- Fwiw, Wikipedia gives Marvin’s gender as “Male design”, but I didn’t find anything definitive.
- 16:47 - I wonder whether “preview” is the right word for those head and tail views of pandas DataFrames, because “preview” implies seeing something before it’s generally available, which doesn’t seem to be the case here. So far, I can only suggest the wordier alternative “head and tail”, just to be consistent with Panda’s own terminology/function names, but that doesn’t cover the horizontal dimension. I suppose “preview” is perfectly fine in the sense of “an incomplete glimpse of” … “coup d'œil”
- 20:16 - I gather `iloc` might be short for “integer location”, or perhaps more meaningfully “locate by integer”, in case that somehow helps demystify it for newcomers. I suppose it is in contrast to `loc`, which is to access “location by label”, and `ix` (aka Ford Prefect! What is a Hrung?) for mixed integer/label access.
- 22:43 - Might be worth clarifying that the stop number in slicing is exclusive, whereas the start number is inclusive. (Compare to genomic start and end positions?) For example, `0:5` is the set {0,1,2,3,4} rather than {0,1,2,3,4,5}.
- 24:33 - At first I didn’t miss the omission of mentioning multiple/multi-level indexes, at this stage, because it might have been too advanced/confusing, but we do see multiple emboldened columns without any mention later (c. 30:54)
- 30:09 - I did wonder whether it would be worth mentioning the quote marks in the query string, but decided it wouldn’t be missed.
- 30:54 - Might want to briefly explain why multiple columns appear in bold (indexes) in the `vgsc_ns_snps` DataFrame, which wasn’t introduced/explained earlier.
- 38:49 - It was all just an elaborate build up to that punchline! :-) ...Worth it!
- 40:55 - Why didn’t you have to import Plotly Express? (`px`)

**Comment by alimanfoo** [comment]
Thanks so much @leehart :smile: :pray:
