### ISSUE TITLE
Workshop 2 - module 2 (metabolic resistance) - feedback from Lee

### ISSUE THREAD

**Issue by leehart** [anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io#45]
@bstlaure 

Great video! Easy pace. Very informative and presented very clearly.

As usual, only very minor thoughts to offer:
- It would be nice to see a video of the presenter — although not essential, obviously.
- 4:48 - I really appreciated the explanation of the Cyp9K1 gene name. (And the GSTe2 at 6:40.)
- 5:21 - Just for fun: https://www.reddit.com/r/MapsWithoutNZ/
- 7:36 - It seems a bit odd to have figure descriptions that are too long to read in real time, but I don’t know if students can pause the video.
- 10:00 - Maybe clarify how / why mutations in CNV genes are “evolutionarily cheap” — just because that sounds intriguing.
- 18:29 - A nice clear summary to end on!
- Some inconsistencies in capitalisation at the beginning of bullets. (I’m here for the important stuff!)

**Comment by bstlaure** [comment]
poor New Zealand! Thanks for the suggestions
