### ISSUE TITLE
Missing link in Workshop 1 module 2 exercise

### ISSUE THREAD

**Issue by EricRLucas** [anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io#57]
@alimanfoo @jonbrenas wasn't sure where best to flag this. In workshop1, module 2, exercise 5, the hyperlink to the ipyleaflets basemaps documentation is missing in the French version of the questions.

**Comment by alimanfoo** [comment]
Thanks @EricRLucas, should be fixed now.
