### ISSUE TITLE
Workshop 3 - module 1 (Plotly Express) - feedback from Lee

### ISSUE THREAD

**Issue by leehart** [anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io#70]
@alimanfoo 

Another great tutorial! Seems useful, rational, reasonable, helpful. The tone seems down-to-earth and personable.

I only have some very minor and vague comments/thoughts to offer:

- Sound quality seems good and clear. It might be a touch bassy, but that could be my speakers, and I don’t think it’s significant.
- The preamble about the different use cases for different plotting libraries seems a little bit wordy, so might benefit from a brief visual example of each.
- I wondered if the term “observation” might carry some counterproductive baggage/confusion in the scientific realm — although it is certainly useful here. Fwiw, another way I’ve seen the difference between “wide” and “long” data formats being summarised is in terms of repeated (or “stacked”) values/groups/categories, either with respect to the columns or the rows, e.g. https://www.statology.org/long-vs-wide-data/ and https://www.theanalysisfactor.com/wide-and-long-data/ , but I think the approach you already have might be clearer.
- The loading of Gapminder data into DataFrame was explained very well. I wouldn’t worry too much, personally, about the audience worrying about the data’s origin/wrangling in this situation, since we’re here to look at plotting. As long as we can see a preview of the actual data that will be used for plotting, and the way you’ve explained it all seems very accommodating/considerate to me.
- When you started adding new info into a plot’s hover text, I started to wonder about the difference between plots that are made for static presentations (e.g. print) and plots that are made for exploration/analysis (e.g. interactive). The option of saving the plot as an image is mentioned later, so I’m thinking perhaps there might be a way to address these different use-cases more directly / upfront. But maybe this haze is just an unavoidable side-effect of a transition in the industry towards supporting more interactive plots. Perhaps the module just needs a bit of preamble about what can be done with plots once they’ve been created, in terms of sharing.
- 19:15 — Maybe quickly click through to show the Plotly docs page about hover text, as a brief preview, to soothe curiosity.
- I’ve noticed some use of American English (not just in programming languages, where we don’t have a choice), e.g. one of the exercise descriptions uses “color”. I don’t know if this is a conscious decision or just inevitable lingua franca. Fwiw, I would guess American English would be the most convenient choice, and have a larger audience, and I wondered about any potential need to keep that consistent. It’s not practically important, because of the mutual fluency, but it might seem culturally blasé.
- It’s always great to see time-series data plotted and animated, and made interactive. =) Of course, after that, I was rather hoping to see a 3D plot!
- 33:27 — “perfect is the enemy of good” — Yeah, I often think about that idea, and I still wrestle with it, philosophically. (I might call myself a “recovering perfectionist” or a “reluctant pragmatist”, and I’m a fan of wabi-sabi.) The aphorism seems related to “If you never miss a plane, you’re spending too much time at the airport.” (George Stigler) which seems to ignore all the waiting at airports caused by missing planes, just as imperfections are often bad, almost by definition, and “perfect” is often perfectly good. So I like the maxim: every proverb has an equal and opposite proverb. (Except perhaps that one?! Reminds me of Russell's paradox…)
- 34:50 — TIL: the term “munging” (dating back to at least 1958) is often said to be from the acronym Mash Until No Good, but that actually seems to be a backronym from 1960. It looks like “mung” was originally used in a destructive sense (e.g. to mess up data) but now it means almost the opposite, similar to “duct-taping” (in the data-wrangling sense) and the way you’re using it to gloss over data transformations/manipulations. I'm told that in the old computer game “Zork” (circa 1978) you can destroy things using the “mung” command (which has aliases such as “mangle” and “break”, etc.) For example, at the beginning of Zork, it says “A rubber mat saying ‘Welcome to Zork!’ lies by the door” and you can type “mung mat”, and it will say “Trying to destroy a welcome mat isn’t very interesting.” https://en.wikipedia.org/wiki/Auto-antonym
- It was good to return to the difference between wide and long data structures. I expect any repetitions and reminders will be good for teaching/learning.
- 40:15 — It was great to see those analytical payoffs demonstrated — using plots to clearly bring out higher-level information, from otherwise quite opaque data tables.

**Comment by alimanfoo** [comment]
Illuminating and entertaining feedback as always, thanks @leehart :smile:
