### ISSUE TITLE
Workshop 3 - module 3 (SNP data) - feedback from Lee

### ISSUE THREAD

**Issue by leehart** [anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io#72]
Hi @alimanfoo

I thought the video was very informative, gentle-paced, demystifying and very helpful, and enjoyable. It seems like a great intro to big data, cloud computing and the IGV tool, and lots of SNP-data related concepts. 

As usual, only minor comments to offer:

- 2:25 — I only noticed this once, and I expect it will probably disappear in future drafts, but you could probably maintain your usual confident tone, to avoid seeding any unnecessary doubt/unreceptiveness in the audience.
- I’m a bit worried that the whole refresh-until-USA dance seems a little hacky and implementation-specific/circumstantial — if only it didn’t make such a difference! It’s a shame there isn’t a way to force/request a performant VM. I suppose the silver-lining is that it serves as a teaching point.
- 10:54 — I think you said “50 million megabases” but meant either “50 megabases” or “50 million bases”.
- I enjoyed the explanation of the discrepancy between the number of SNP calls versus the number of ref sites, and your very dry humour around that being noticeable! =)
- 29:30 — It wasn’t super-clear (imo) why loading all of the variant_allele values into local memory was OK, whereas trying to load all of the call_genotype values would crash. (Especially since each variant_allele is 4 characters, whereas each call_genotype is only 2 integers.) Maybe providing a reminder of the hard numbers would help hit this home, because it seems (to me) like a super-helpful point to make.
- 34:15 — I liked the idea of explaining the allele counting process while snp_allele_counts was actually running, as an illustration of computing with big(ish) data.
- I look forward to a more polished description of the site filters. (My own understanding still feels a bit muddy, maybe because of the old notion of “accessibility”.) I expect that will round off the video very nicely.

**Comment by alimanfoo** [comment]
Thanks so much @leehart :pray:
