### ISSUE TITLE
Workshop 3 - module 4 (PCA for pop. structure) - feedback from Lee

### ISSUE THREAD

**Issue by leehart** [anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io#73]
Hi @cclarkson

Very informative and clear. Important and well-needed, and delivered with a heartening professional tone.

I only have a few very minor comments/thoughts to offer:

- I suppose a couple of relevant pictures or diagrams before the 3:45 minute mark would be nice, but I don’t know what to suggest.
- The video was very choppy (a technical term) between about 6:28 and 9:35. (I guess to do with the computer issues you mentioned.) The sound quality seemed unchanged during that period though — just the background white-noise throughout.
- 8:02 — I reckon “biallic” should be “biallelic” in the text for “behind the scenes” of `pca()`.
- 13:55 — I wouldn’t personally say “do the dot head notation”. Maybe “call the head function” instead.
- 14:12 — Personally, I would edit part of the text below the `data.head()` cell to “mosquito sample, e.g. its sample ID, collection site, taxon, etc.” — i.e. add a couple of commas, remove an apostrophe, and remove the italics.
- 19:40 — I reckon floating-point numbers are not actually/technically “real” numbers, in the mathematical sense, only a representation, but that’s probably splitting hairs. https://en.wikipedia.org/wiki/Real_number#In_computation
- For me, there’s always something unsatisfying about dismissing weak signals as "just noise", but I accept that’s pragmatic and an important teaching point here. And I've probably just seen too many movies!

**Comment by cclarkson** [comment]
Many thanks @leehart for the useful comments and thoughts.
