### ISSUE TITLE
Workshop 4 module 4 - comments from Jon

### ISSUE THREAD

**Issue by jonbrenas** [anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io#79]
- I am not sure what you want to say when you show (~17 min) that the sets of labels for aim_species and taxon are the same. It makes more sense after the exemple for TZ but I think it would be better to show that all the samples that were pulled by PC2 (in the TZ case) are now called as 'gcx3' by showing the same PCA but with coloring based on taxon.  
- Maybe have a few more (and more specific) pictures to avoid having to go back to the big AIM plot with all the samples
- Should we make sure that it is clear to the students that the explanation "Arabiensis can survive in the desert while gambiae cannot" is AN explanation consistent with other observations and maybe not THE explanation?
- The KE section would lead me more towards deciding that there are 2 cryptic species in the East that may be related and is thus a little bit confusing

**Comment by cclarkson** [comment]
Thanks for the comments @jonbrenas :+1:
