### ISSUE TITLE
Workshop 1 - module 1 (colab) - feedback from Lee

### ISSUE THREAD

**Issue by leehart** [anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io#8]
On the whole, I felt this was a great primer.

Some thoughts I’d noted, all very minor:
1. It would be nice if the presenter video could be moved so that it didn’t obscure any text/UI, but I suspect this isn’t doable/feasible with the given tech. It doesn’t cause any major issues until the end of the video, when the share button is obscured (44:30).
2. Contrariwise, it would also be nice to see a bigger presenter video, at the expense of obscuring more. I reckon at least 4 times bigger. Again, I suspect there’s a tech limitation.
3. I had wondered whether it would be clarifying to refer to “notebooks” as “Jupyter notebooks”, at least at first, but then I noticed that Google Colab doesn’t expose that either, saying “Colab notebooks are Jupyter notebooks that are hosted by Colab.” I suppose “notebook” is a natural genericization, and the context renders anything like “digital notebook” superfluous.
4. I imagined that the initial jump into “writing some code” might be a bit sudden/scary to those unfamiliar with programming, although it shouldn’t be surprising in the context, and it has to start somewhere. Perhaps a slightly softer intro, although intros don’t get much gentler than Hello World!
5. It would be nice if the sound quality was better, but I expect that would require getting a fancy microphone.
6. It would be nice if the hotkey combinations that are mentioned are visible onscreen, but I suspect tech limitations. Instead, it might be possible to get the shortcut combos displayed through the available tooltips.
7. Related to the mentioning of hotkeys, it would be nice if some sort of downloadable cheat-sheet or summary of the lesson was provided, or perhaps advise viewers to be taking notes.
8. Another nice tech enhancement would be to have the sections of the video visible, ideally on the timeline control. Instead, it might be useful to show and mention the sections beforehand, or provide section headings in a downloadable video summary.
9. It seemed odd or potentially confusing to show the tools for bold, italic, hyperlink, etc., but never apply them, and then show the manual Markdown code instead. I suspect viewers who are not familiar with Markdown might lean towards using the toolbar anyway, since it’s there. I do think it’s important to show the Markdown, so perhaps it’s just the equivalence that needs pointing out.
10. I feel it would be good to reassure the viewer towards the beginning, rather than towards the end, that their notebook will be easily saved, downloaded and shared.
11. Since we’re using British English, and since the birth of the hashtag, I expect referring to # as “the hash character” is safe, even if it’s often called something else in American and Canadian English, e.g. “the number sign” or “the pound sign”. I expect there’s a lot of American English documentation online that won’t call it the hash character, e.g. on markdownguide.org and ibm.com. It might be more cosmopolitan to say “the hash character, also known as the number sign”, but I suspect it’s a worry about nothing. 
12. At the risk of making the video longer, as someone who edits a lot of notebooks, I expect a quick demonstration of how to copy and paste cells in Colab might be appreciated. Although, maybe that feature is still a bit janky, or potentially problematic.
13. After first introducing numpy and mentioning that numpy is useful, it raises the question of what it might be useful for. Perhaps mention a couple of examples, even though numpy will be used later on.
14. I felt that functions were explained well, but then when packages were introduced, there seemed to be a delay in explaining the utility of a package (with relation to functions). It was all explained eventually but perhaps it would help to tweak the sequence of mentions, so that the idea of importing a package in order to use its functions hits first, after introducing the utility of functions.
15. It might be my imagination, but I think “malariagen_data” was misspoken as “malariagen_datalab” around 25:57
16. There seemed to be the suggestion that the module was almost over around 27:07
17. I might be hearing things again, but I think “30 coins” was misspoken as “50 coins” around 33:19
18. My only suggestion for cutting the time down would be to only show the Plotly example. I felt that plotting with 2 different plotting libraries might have been overkill, although I was expecting Bokeh to be shown too. I expect it would suffice to just mention one or two certain differences, but I would avoid implying that Matplotlib can’t produce interactive plots. The practical exercises seem to require some independent investigation into those libraries, so just one worked-through example seems sufficient to me.
19. Again this might be an unavoidable technical issue, but the mouse pointer seems to create some lagging artefacts when scrolling, e.g. 42:41. Perhaps that could be worked around by keeping the mouse pointer out of the way when scrolling.
20. 44:13 to 44:30 one of the joys of recording :-)

**Comment by alimanfoo** [comment]
Hopefully mostly resolved via [new recording and lecture notes](https://anopheles-genomic-surveillance.github.io/workshop-1/module-1-colab.html), thanks again @leehart :pray:
