### ISSUE TITLE
Workshop 4 module 1 - comments from Jon

### ISSUE THREAD

**Issue by jonbrenas** [anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io#80]
- Is the size of data of much concern for the students (or at least, the ones that do not yet know about this issue)?
- Our 3D-arrays are not shown that way, which can be confusing
- At ~22 min, you say that creating an array of 1s (or 0s) is more useful than we would think but don't really explain why.
- I think the last example of indexing (at ~ 31 min), is to show how slices work ([0:2] is "take everything between tick 0 and tick 2") It is the usual gap & post problem. I know that it is (for instance) confusing for R users (where slices include the last element)
- I agree with the statement at 32:37 that I will have a blast doing the translations
- If we look at the dtype of the objects, maybe it is worth showing how you set the dtype (in particular, for np.ones, where the default dtype isn't quite intuitive)
- Are enough of our students math-aware that they may be confused that products of matrices (i.e., 2D-arrays) are not matrix-products?
- In the computation of the mean square error, why not use the mean?

**Comment by alimanfoo** [comment]
Thanks so much @jonbrenas, great comments.
