### ISSUE TITLE
Workshop 4 module 3 - comments from Carlo

### ISSUE THREAD

**Issue by randomxsk8** [anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io#81]
Hi @alimanfoo sorry for the late reply! I've seen all the modules of the workshop and they're great!
I would like to ask you if it is possible to split AIMs based on chromosomes and show the variant locator.. could be useful? Or maybe add on the hover description the specific location for that AIM in the genome.
This maybe useful for the reader to understand which regions are heterozygous or introgressed (like the 2L region in BFcol).
Another pretty thing that i think is to show at the beginning maybe with a table how many AIMs are for each chromosome..
What do you think?

**Comment by alimanfoo** [comment]
Hi @randomxsk8, great comments, thank you! I have fixed the plots to split by chromosome arm, and will include counts of AIMs per chromosome. For some reason I'm finding it hard to get the actual variant positions into the hover labels, and haven't had time to figure out how to do variant locators in plotly, so will have to add them later on if possible.
