### ISSUE TITLE
Workshop 4 module 1 - comments from Brandy

### ISSUE THREAD

**Issue by bstlaure** [anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io#83]
nice examples of vector and matrix type arrays

maybe describe tuples a bit further

when discussing data types, a brief overview of what data types there are (maybe an image describing these with them written out with a few examples of each), you mention these as you go along, but I think you should give an overview with something written to look at while you describe them and then briefly mention them again as you use them or the dtype function.

emphasize that dtype is a really useful check

I don't know that data.size *data.itemsize is really useful - do you use this?

23:58 - explain briefly why do you need two "random"s in np.random.random(3) ?

as you are creating different types of arrays, mention once somewhere that what you are naming the arrays is arbitrary, and that you are creating array objects

29:25 Very important revisiting of zero-based indexing - is it worth having another visual of the Numpy Array as above with the index listed next to the array? Even though we've covered this a few times, I think people are still struggling with it.

31.26 Nice visual examples of slicing , and I think the next section on two dimensional arrays is useful too. I don't think you should worry about time, the more time spent on this super useful stuff, the better

36:36 I think you could explicitly label "output array" or "output" to the right in grey or above the arrays in the following examples as you have "data" and "ones" above the other arrays

Could you give an example of how to append arrays? Perhaps calculate a new column and append it to the original array?

We've had repeated questions about how to save things - perhaps an example of how to save an output array that they have calculated to a csv or tsv file? maybe as an exercise?

I think Boolean arrays and everything after could be part of the data module in the next workshop. Could you build a whole module about Boolean arrays and doing array calculations? I think you risk losing the students getting into anything more complex here and what you have covered thus far is on a pretty similar level of complexity, this stuff at the end seems like another big jump that might overwhelm students right as they are getting the hang of np arrays. Perhaps just mention Boolean arrays and that we will dig into these further in a future workshop?

**Comment by alimanfoo** [comment]
Thanks so much @bstlaure, great comments.
