### ISSUE TITLE
Workshop 4 - module 3 (AIMs) - feedback from Lee

### ISSUE THREAD

**Issue by leehart** [anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io#87]
Hi @alimanfoo

Another great training module. :-)
I thought this was a nice way to follow the cryptic tax module.
I reckon it’s very important and, dare I say, “informative”.

- Clear intro & setup.
- Good sound quality. Clear and crisp. Maybe low volume, but easily rectified at my end.
- In the AIM plots, I don’t remember hearing an explanation (maybe because it would get too technical) for why the samples (rows) in the plot appear to be grouped together, as if by species, i.e. rows with the same colouring/taxonomy (roughly) appear next to each other. What determines the sort order? (It can’t be random or lexicographical.)
- 34:03 - I thought that the plot showing that the AG1000G-GW set had no arabiensis (i.e. all samples were homozygous gambcolu) was quite helpful as a clarification, partly because you’d previously pointed out that trying to view AIM plots for gamb_vs_colu calls on purely arabiensis samples results in a hallmark banded pattern, so some might question whether they are seeing here is the same or similar.
- I enjoyed the discussion of AIM-based species classification, which I thought rounded off this module (and the last module, re. species complexes and crypic taxa) quite neatly.

Thanks! Much fun.

**Comment by alimanfoo** [comment]
Thanks so much @leehart :)
