### ISSUE TITLE
Workshop 4 - module 4 (cryptic taxa discovery) - feedback from Lee

### ISSUE THREAD

**Issue by leehart** [anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io#88]
Another great tutorial! Thanks @cclarkson

Only minor thoughts/comments:

- Clear, crisp sound. Maybe a bit low volume, but fixed at my end — no problem.
- 10:54 - “describe it’s variance” should probably be “describe its variance”. (Just delinting your Kiton K-50, Sir.)
- 13:00 - It might be worth saying that `evr` stands for explained variance “ratio”, unless that goes without saying, or raises more questions.
- 20:30 - Interactive 3D plots are just the bee’s knees! :-)
- 23:11 - It’s hard for me to advise here; I’m not sure what needs to be done. FWIW, I suppose there is replicated info on those 3 maps, and only the counts in the taxon column (and maybe the year) seem to add more info, potentially.
- 24:45 - It was probably because I was feeling tired, but I started to feel a bit lost/overwhelmed/out-of-my-depth at this point, WRT analysing, interpreting and explaining PCA clusters on a background of biological information. It might be to do with the level of scientific knowledge/context, complexity, or speculation/investigation required here, I’m not sure. It’s probably just this particular area in general for me personally. It’s certainly interesting, intriguing and scientifically exciting, so it’s difficult to explain. In any case, the slightly disorientated feeling soon passed and the rest of the tutorial seemed like plain sailing!

**Comment by cclarkson** [comment]
Thank @leehart, super helpful. The whole AIM proportion bit defo needs explaining better!
