### ISSUE TITLE
Workshop 5 - module 4 (heterozygosity & ROH) - feedback from Lee

### ISSUE THREAD

**Issue by leehart** [anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io#94]
Many thanks @cclarkson 

Very clear and informative. A fascinating walkthrough.

Not much to say, really. Good stuff!

Part 1:
- 4:00 - I like the emboldened terms.
- 6:35 - I appreciate the note about plotting 53M points being impractical.
- 9:22 - I expect it’s OK to not explain the reason for low heterozygosity at the two ends, any more than you did, although it might spark some curiosity. (No bad thing.) Might be too far off topic/field.
- 11:50 - The bullet text on that figure (lab colony from wild population) is a bit distorted and difficult to read. Reminds me of an old dot matrix printout!
- One of the clearest illustrations of founding effect + genetic drift that I’ve seen. Nice.
- The comparison of the mother and child heterozygosity plots makes me wonder about percentages and probabilities. I don’t suppose anything can be said, statistically/quantitively, about how less heterozygous the child is (or is expected to be) compared to the parents? Or is that just silly?!
- I really like the connections drawn between the cold plotted stats and the real world biological scenarios.

I’m looking forward to part 2. :-)

**Comment by cclarkson** [comment]
Thanks @leehart!
